quarkus.http.port=8488

%dev.quarkus.redis.hosts=redis://localhost:6379
%dev.quarkus.redis.health.enabled=false
%prod.quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
%prod.quarkus.redis.health.enabled=false

%dev.socket-proxy.uri=http://localhost:2375
%prod.socket-proxy.uri=http://${SOCKET_PROXY_HOST:localhost}:${SOCKET_PROXY_PORT:2375}

%dev.container-runtime.network=horizontalscaling
%prod.container-runtime.network=horizontalscaling

%dev.quarkus.rest-client."consul-server".uri=http://localhost:8500
%prod.quarkus.rest-client."consul-server".uri=http://${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

app.connection-rebalancer.container-runtime.app-name="${CONTAINER_RUNTIME_APP_NAME:tracker-app}"
app.connection-rebalancer.container-runtime.grpc-app-name="${CONTAINER_RUNTIME_GRPC_APP_NAME:tracker-app-grpc}"
app.connection-rebalancer.environment.type="${ENVIRONMENT_TYPE:container_runtime}"
app.connection-rebalancer.kubernetes.app-label="${KUBERNETES_APP_LABEL:tracker}"
quarkus.devservices.enabled=false